import {
  LayoutDashboard,
  Droplets,
  Filter,
  Database,
  Share2,
  GitBranch,
  TriangleAlert,
  Gauge,
  Waves,
  Radio,
  Map,
  Brain,
  Wrench,
  Users,
  ChartColumn,
  Bell,
  FileText,
  Settings,
  Fan,
  Activity,
  Layers,
  Box,
  Zap,
  FlaskConical,
  CircleCheck,
  TrendingUp,
  TrendingDown,
  Sun,
  Moon,
  Search,
  Thermometer,
  BatteryFull,
  BatteryLow,
  BatteryWarning,
  Signal,
  SignalLow,
  Wifi,
  WifiOff,
  Factory,
  MapPin,
  Truck,
  CircleDot,
  Clock,
  Download,
  ShieldCheck,
  Cpu,
  ChevronRight,
  Menu,
  X,
  CircleAlert,
  Plus,
  type LucideIcon,
} from "lucide-react"

const map: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  droplets: Droplets,
  filter: Filter,
  database: Database,
  "share-2": Share2,
  "git-branch": GitBranch,
  "alert-triangle": TriangleAlert,
  gauge: Gauge,
  waves: Waves,
  radio: Radio,
  map: Map,
  brain: Brain,
  wrench: Wrench,
  users: Users,
  "bar-chart-3": ChartColumn,
  bell: Bell,
  "file-text": FileText,
  settings: Settings,
  fan: Fan,
  activity: Activity,
  layers: Layers,
  box: Box,
  zap: Zap,
  flask: FlaskConical,
  "check-circle": CircleCheck,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  sun: Sun,
  moon: Moon,
  search: Search,
  thermometer: Thermometer,
  "battery-full": BatteryFull,
  "battery-low": BatteryLow,
  "battery-warning": BatteryWarning,
  signal: Signal,
  "signal-low": SignalLow,
  wifi: Wifi,
  "wifi-off": WifiOff,
  factory: Factory,
  "map-pin": MapPin,
  truck: Truck,
  "circle-dot": CircleDot,
  clock: Clock,
  download: Download,
  "shield-check": ShieldCheck,
  cpu: Cpu,
  "chevron-right": ChevronRight,
  menu: Menu,
  x: X,
  "circle-alert": CircleAlert,
  plus: Plus,
}

export function Icon({
  name,
  className,
}: {
  name: string
  className?: string
}) {
  const Cmp = map[name] ?? CircleDot
  return <Cmp className={className} aria-hidden="true" />
}
